spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      initial-size: 2
      max-active: 50
      min-idle: 2
      stat-view-servlet:
        login-password: druid
        login-username: druid
        reset-enable: true
        url-pattern: /druid/*
      test-while-idle: true
      validation-query: SELECT 1
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:p6spy:mysql://39.97.106.72:3306/improve?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
  rabbitmq:
    host: 39.97.106.72
    port: 5672
    username: guest
    password: guest
mybatis-plus:
  type-aliases-package: com.sun.improve.mybatis.entity
  mapper-locations: classpath*:mapper/*.xml


logging:
  level:
    com.sun.improve.mybatis.mapper: debug
